Revert "Fix bug in husky check"
This reverts commit 2c055f44e216d6b2d158ccf427534fcf2b52ddc3.

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -2,11 +2,14 @@
 . "$(dirname -- "$0")/_/husky.sh"
 
 CODE_CHANGED=$(git diff origin/main --name-only | grep -E "\.(js|ts|json|py)$")
-if [ -n "$CODE_CHANGED" ]; then
-    npm run test
-    VERSION_CHANGED=$(git diff origin/main package.json | grep '"version":')
-    if [ -z "$VERSION_CHANGED" ]; then
-      echo "ERROR: You must update package.json version before pushing to main!"
-      exit 1
-    fi
+if [ -z "$VERSION_CHANGED" ]; then
+  echo "No code changes detected. Skipping tests."
+  exit 0
+fi
+
+npm run test
+VERSION_CHANGED=$(git diff origin/main package.json | grep '"version":')
+if [ -z "$VERSION_CHANGED" ]; then
+  echo "ERROR: You must update package.json version before pushing to main!"
+  exit 1
 fi
